### PR TITLE
Modify

### PR DESCRIPTION
**Pull request by kerbecs**
New line added

### CODE REVIEW

**Comment by edic21** [comment]
Your new line is to short.

**Comment by kerbecs** [comment]
now it's ok

**Comment by kerbecs** [comment]
try and add an example

**Comment by kerbecs** [comment]
somethig else to do?

**Comment by edic21** [comment]
try and add an example

**Review by edic21 — CHANGES_REQUESTED** [review]
A line more should be ok

**Review by edic21 — APPROVED** [review]

**Comment by edic21** [comment]
Add an info file

**Comment by kerbecs** [comment]
and what to write in?

**Review by edic21 — APPROVED** [review]

**Comment by edic21** [comment]
> Add an info file

**Comment by edic21** [comment]
do you want to add someting new?

**Comment by kerbecs** [comment]
no

**Comment by edic21** [comment]
I'll try something new

**Pull request merged**
